
jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000000
  refresh-token-expiration: 864000000



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1996
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
telegram:
  bot:
    username: "MyFJavaBot"
    token: "7218034229:AAH_nKLUiujNnvUwgmfbwzZL2IVurSqc-EU"
    chanel-id: "@myjavachan"
    file: "/home/bobur/test/backup"
